#ifndef SKYMP_WIRE_H
#define SKYMP_WIRE_H

/* Generated by cbindgen from wire-client-ffi. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The callback `Tick` calls once per event: packet type, content and its
 * length, an error text (never null), and the caller's state. Null is
 * allowed and means "drop the events".
 */
typedef void (*OnPacket)(int32_t, const char*, size_t, const char*, void*);

/**
 * The version string. Nothing in skymp5-client reads it; it marks the wire.
 */
const char *MpCommonGetVersion(void);

/**
 * Start connecting to `host:port`, replacing any client that exists.
 * Progress arrives through `Tick`.
 *
 * # Safety
 * `host` is null or a valid NUL-terminated string, borrowed for the call.
 */
void CreateClient(const char *host, uint16_t port);

/**
 * Disconnect and forget the client.
 */
void DestroyClient(void);

/**
 * True while the connection is up.
 */
bool IsConnected(void);

/**
 * Deliver every pending event to `on_packet`, oldest first.
 *
 * # Safety
 * `on_packet` is null or a function with the [`OnPacket`] signature;
 * `state` is passed back to it untouched.
 */
void Tick(OnPacket on_packet, void *state);

/**
 * Send one SkyMP message, given as its JSON (what skymp5-client's
 * networking service passes).
 *
 * # Safety
 * `json` is null or a valid NUL-terminated string, borrowed for the call.
 */
void Send(const char *json, bool reliable);

/**
 * Send raw bytes. Nothing in skymp5-client emits a raw send; for the
 * export's sake, bytes that are SkyMP JSON (with or without the 0x86 packet
 * id in front) are sent as `Send` would, anything else is refused.
 *
 * # Safety
 * `data` points to `size` readable bytes (or is null with `size` 0),
 * borrowed for the call.
 */
void SendRaw(const void *data, size_t size, bool reliable);

#endif  /* SKYMP_WIRE_H */
