#ifndef SKYMP_WIRE_H
#define SKYMP_WIRE_H

/* Generated by cbindgen from wire-client-ffi. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * A slot that was not filled.
 */
#define KIND_NONE 0

/**
 * `Message::Welcome`.
 */
#define KIND_WELCOME 1

/**
 * `Message::Refuse`; `reason` is set.
 */
#define KIND_REFUSE 2

/**
 * `Message::InventoryApply`; `actor` is the owner, `target` the item,
 * `count` the signed count.
 */
#define KIND_INVENTORY_APPLY 3

/**
 * `Message::HostGrant`; `actor` is the cell.
 */
#define KIND_HOST_GRANT 4

/**
 * `Message::HostRelease`; `actor` is the cell.
 */
#define KIND_HOST_RELEASE 5

/**
 * Opaque client handle.
 */
typedef struct Client Client;

/**
 * Event view handed to C++. Mirrors wire-bridge's flattening; keep in sync.
 */
typedef struct SkympWireEvent {
  /**
   * One of the `KIND_*` constants.
   */
  uint32_t kind;
  /**
   * Message sequence number, when the message has one.
   */
  uint32_t seq;
  /**
   * Primary form id (owner, cell).
   */
  uint32_t actor;
  /**
   * Secondary form id (item).
   */
  uint32_t target;
  /**
   * Weapon form id.
   */
  uint32_t weapon;
  /**
   * World x.
   */
  float x;
  /**
   * World y.
   */
  float y;
  /**
   * World z.
   */
  float z;
  /**
   * Heading, radians.
   */
  float yaw;
  /**
   * Look pitch, radians.
   */
  float pitch;
  /**
   * Flag bits per kind.
   */
  uint32_t flags;
  /**
   * Signed item count for inventory events.
   */
  int32_t count;
  /**
   * Reason code for `KIND_REFUSE`, else 0.
   */
  uint16_t reason;
} SkympWireEvent;

/**
 * Connect to `addr` (NUL-terminated `ip:port`) with a token of `token_len`
 * bytes. Returns null on failure. Caller frees with `skymp_wire_disconnect`.
 *
 * # Safety
 * `addr` must be a valid NUL-terminated string; `token` must point to
 * `token_len` readable bytes. Neither is retained after return.
 */
struct Client *skymp_wire_connect(const char *addr, const uint8_t *token, uintptr_t token_len);

/**
 * Advance by `dt_ms` and fill `out` with up to `cap` events, oldest first.
 * Returns the count written. Events not returned this call are returned
 * next call.
 *
 * # Safety
 * `client` must come from `skymp_wire_connect` and not yet be disconnected;
 * `out` must point to `cap` writable `SkympWireEvent`s.
 */
uintptr_t skymp_wire_poll(struct Client *client,
                          uint64_t dt_ms,
                          struct SkympWireEvent *out,
                          uintptr_t cap);

/**
 * Send a movement sample. Returns false if the client is gone.
 *
 * # Safety
 * `client` must be a live handle from `skymp_wire_connect`.
 */
bool skymp_wire_send_movement(struct Client *client,
                              uint32_t seq,
                              uint32_t actor,
                              float x,
                              float y,
                              float z,
                              float yaw,
                              float pitch,
                              bool run,
                              bool sneak);

/**
 * Disconnect and free. `client` is invalid after this call.
 *
 * # Safety
 * `client` must come from `skymp_wire_connect` and must not be used afterwards.
 */
void skymp_wire_disconnect(struct Client *client);

#endif  /* SKYMP_WIRE_H */
