# skymp-wire in the CMake build (thuum ADR-019). Corrosion runs cargo over
# the workspace at skymp-wire/ and imports its artifacts as CMake targets,
# passing CMake's compilers to whatever C or C++ the crates build. The cxx
# glue for wire-bridge is generated by cxxbridge and compiled here, by the
# same compiler and C++ library as the server it links into.
#
#   wire_bridge_cxx  the bridge the server addon (WireServer.cpp) and
#                    server_guest_lib (the game rules) link
#   fakeclient       the lab's headless client, placed in dist/server (not Windows)
#   skymp_wire       the client DLL, shipped as MpClientPlugin.dll (Windows)
include_guard(GLOBAL)

include(FetchContent)
FetchContent_Declare(Corrosion
  GIT_REPOSITORY https://github.com/corrosion-rs/corrosion.git
  GIT_TAG v0.6.1
)
FetchContent_MakeAvailable(Corrosion)

if(WIN32)
  set(wire_crates wire-bridge wire-client-ffi)
else()
  set(wire_crates wire-bridge wire-fakeclient)
endif()

corrosion_import_crate(
  MANIFEST_PATH "${CMAKE_SOURCE_DIR}/skymp-wire/Cargo.toml"
  CRATES ${wire_crates}
  LOCKED
)

# lib.rs: the transport the addon polls; rules.rs: the game rules the server
# library asks (thuum ADR-020), so server_guest_lib and its unit tests link it
corrosion_add_cxxbridge(wire_bridge_cxx CRATE wire_bridge FILES lib.rs rules.rs)

if(MSVC)
  # The Windows build links the static C runtime (cmake/apply_default_settings,
  # triplet x64-windows-sp): the Rust code, the C++ that cc-rs builds for the
  # crates, and the cxx glue must use it too, or MSVC refuses the mixed link.
  foreach(wire_target wire_bridge skymp_wire)
    if(TARGET ${wire_target})
      corrosion_add_target_rustflags(${wire_target} "-Ctarget-feature=+crt-static")
    endif()
  endforeach()
  set_target_properties(wire_bridge_cxx PROPERTIES
    MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()

if(NOT WIN32)
  # lab-api's `server: fakeclient` steps and `just test-proto` run it from the
  # server image, next to the server
  set_target_properties(fakeclient PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/dist/server")
endif()
